### ISSUE TITLE
Unexpected Run-lengths - possible infinite looping.

### ISSUE THREAD

**Issue by wknechtel** [thebitpusher/boxologic#6]
Some of the tests (after band-aid-ing some bad free() calls) run for extraordinarily long times, so much so that I believe we've got some infinite loops.  I halted one execution of test/mpp04.txt after it had been running for ~30 min.   Since the longest solution time in the original thesis was 12 seconds, I think it's safe to same something's not right.  My hunch is that something was transcribed incorrectly.

**Comment by haris989** [comment]
So was this finally fixed?
